<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>leaf</string>
		<string>lf</string>
		<string>lef</string>
	</array>
	<key>name</key>
	<string>HTML (Leaf)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.leaf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.leaf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.begin.leaf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.other.end.leaf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#{1,2})(\w*)?(\({1,})([^)]*)(\){1,})\s*</string>
			<key>name</key>
			<string>meta.tag.leaf</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.leaf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.begin.leaf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.htm</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.end.leaf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#{1,2})(\({1,})([^)]*)(\))</string>
			<key>name</key>
			<string>meta.variable.leaf</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.leaf</string>
	<key>uuid</key>
	<string>95484ff0-9b11-47c7-aa6b-90eeff6eb3ed</string>
</dict>
</plist>
